// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK_C5R1_fxpge6jjm5Q-LJJk-EgEa_heQ',
    appId: '1:1064421623608:web:53dcd6538fa2b2493ca3cd',
    messagingSenderId: '1064421623608',
    projectId: 'leveling-b7d01',
    authDomain: 'leveling-b7d01.firebaseapp.com',
    storageBucket: 'leveling-b7d01.firebasestorage.app',
    measurementId: 'G-50CK4JX6SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx2EnQWEUY5L5Cbz6UmJuwhfnOX-EESTo',
    appId: '1:1064421623608:android:e482b5a0eef3e2ce3ca3cd',
    messagingSenderId: '1064421623608',
    projectId: 'leveling-b7d01',
    storageBucket: 'leveling-b7d01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdrV2GaZArFcqhOXEG6VXgrhgp8VWDZY0',
    appId: '1:1064421623608:ios:181b41d84f6340a43ca3cd',
    messagingSenderId: '1064421623608',
    projectId: 'leveling-b7d01',
    storageBucket: 'leveling-b7d01.firebasestorage.app',
    iosClientId: '1064421623608-qkfm07n9fa47k5l2ov35tclgvj3flead.apps.googleusercontent.com',
    iosBundleId: 'com.example.myleveling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdrV2GaZArFcqhOXEG6VXgrhgp8VWDZY0',
    appId: '1:1064421623608:ios:181b41d84f6340a43ca3cd',
    messagingSenderId: '1064421623608',
    projectId: 'leveling-b7d01',
    storageBucket: 'leveling-b7d01.firebasestorage.app',
    iosClientId: '1064421623608-qkfm07n9fa47k5l2ov35tclgvj3flead.apps.googleusercontent.com',
    iosBundleId: 'com.example.myleveling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK_C5R1_fxpge6jjm5Q-LJJk-EgEa_heQ',
    appId: '1:1064421623608:web:868dab1c320b72053ca3cd',
    messagingSenderId: '1064421623608',
    projectId: 'leveling-b7d01',
    authDomain: 'leveling-b7d01.firebaseapp.com',
    storageBucket: 'leveling-b7d01.firebasestorage.app',
    measurementId: 'G-L56470YH31',
  );
}
